IMPUT_PATH = './output/download_ons_converted/'
BDO_DOWNLOAD_PATH = './output/arquivos_boletim_diario/'
CONVERTED_FILES_PATH = './output/arquivos_boletim_diario/boletim_diario_convertido/'
REGIOES = ['Sistema Interligado', 'Norte', 'Nordeste', 'Sudeste ', 'Sul']
SHEETS_BALANCO_ACUMULADO = 'Balanço de Energia Acumulado' 
SHEET_BALANCO_DIARIO = 'Balanço de Energia' 
#SHEETS_PRODUCAO = ['Produção Hidráulica', 'Produção Térmica', 'Produção Eólica', 'Produção Solar']
SHEETS_PRODUCAO = ['Produção Térmica']
SHEET_MOTIVO_DESPACHO = 'Motivo do Despacho Térmico'
SHEET_RESERVA_GIRANTE = 'Reserva Girante Demanda Máx.'
SHEET_ENERGIA_ARMAZENADA = 'Variação Energia Armazenada'
SHEET_ENERGIA_NATURAL_AFLUENTE = 'Energia Natural Afluente'
SHEET_CARGA_HORARIA = 'Carga Horária'
SHEET_DEMANDA_MAXIMA = 'Demanda Máxima'
SHEET_RESERVATORIOS_HIDRAULICOS = ['Sit. Princ. Reservatórios S', 'Sit. Princ. Reservatórios SE', 'Sit. Princ. Reservatórios NE', 'Sit. Princ. Reservatórios N']